### ISSUE TITLE
"yarn global add leviosajs" does't work properly on Linux when you run without sudo

### ISSUE THREAD

**Issue by devMozao** [bragamat/leviosajs#37]
### The problem
- The problem was found when I installed the package using the command provided on the docs: `yarn global add leviosajs`. After installing it globally, it didn't run or recognized the `leviosa-new` command.

### How to reproduce the problem
- just install it with yarn v:1.22 with the command `yarn global add leviosajs`. I'm running on Linux Mint, most recent build (early 2020).

### Observations
- After doing the step described on the problem above, you would receive a message that everything was installed succesfully (wich is not). Maybe add a test to see if the leviosa-new command was successfully found on bash variables, I guess. (and doing a fallback to undo/uninstall when this happens, maybe even notifying that you should run on sudo).

- The problem didn't occurred when I run the command with `sudo yarn global add leviosajs`. After that, my autocomplete recognized the syntax and validation of the command `leviosa-new app`, and worked perfect without errors.

**Comment by bragamat** [comment]
Hey, getting back on this issue and the options is just to use it as a dev dependency...

try: 
`yarn add -D leviosajs`

and then you can use just like:

`yarn leviosa-new YOUR_APP`
